### ISSUE TITLE
Project still not working

### ISSUE THREAD

**Issue by mroberts1** [Jekyll-Garden/jekyll-garden.github.io#11]
I'm trying again to deploy this template as a GH pages project (i.e. not using <username>github.io as the site root). The page itself is created but displays only as raw text without the theme. 

I have several questions:

1. When I click on Use this template, should I check  "Include all branches"? 

2. In _config.yml, I am then setting the baseurl as </projectname> and the url as <mroberts1.github.io>. Is that correct?

3. Do I need to create a gh-pages branch and add a .github/workflow/jekyll.yml file to it in order to get GH Pages to deploy it, or should it deploy as-is?

4. Alternatively, do I need to choose the Jekyll option from the GH Actions page to get the project to build properly?

Thanks for your help with this.

**Comment by hfactor** [comment]
1. Both are fine, what you need is there in the main branch. 
2. Yes
3. As-is is fine. Github page now supports any branch
4. Nope. No need. 

Check documentation at https://jekyll-garden.github.io/posts/how-to
I will add point 1 to that doc so that it's clear for everyone.

**Comment by makayla-moster** [comment]
I'm also having this trouble trying to deploy this as a template **from a project repository** at [makayla-moster.github.io/note-garden](https://makayla-moster.github.io/note-garden/).

The theme isn't displaying correctly, is there something I've done incorrectly? I was super hype for this template to work with GH pages and it isn't, unfortunately.

My code is [here](https://github.com/makayla-moster/note-garden).

**Comment by makayla-moster** [comment]
@UnipiNotes so there's no way to host this project outside of _yourusername.github.io_? I use that for my personal website and would rather keep the two separate.

**Comment by UnipiNotes** [comment]
@makayla-moster I'm pretty sure that you can. I just recommended that way cause that's the "official" way according to the docs. My solution would be to change the **_config.yml**, specifically the **baseurl**.

Let's say that your repo has the name _note-garden_, your **baseurl** should be _/note-garden_. But now you will have broken links and in general the assets won't work. 

What you have to do is, go to any html layout/include and check the links and assets and make sure they are correctly linked to _note-garden_. You can easily do that by just applying `{{site.baseurl}}` in that link.

For example a link that I see in the navbar should be changed to `{{site.baseurl}}/posts`, it will then correctly point out to /note-garden/posts.

Note: I would first test the site a lot after changing the baseurl and inserting `{{site.baseurl}}` to links just to make sure that everything works.

**Comment by hfactor** [comment]
@makayla-moster : I just forked the repo, created one named [sub-notes and it's working fine. ](https://hiran.in/sub-notes/) (The UI is different as homepage CSS is loading over this sub-domain)

Here is what I did : 

1. Went to the [Project page](https://github.com/Jekyll-Garden/jekyll-garden.github.io), and forked by clicking "Use this template" 
2. Named it "sub-notes"
3. Modified [config.yml](https://github.com/hfactor/sub-notes/blob/main/_config.yml) line 23 and 24 
```
baseurl: "/sub-notes" 
url: "" 
```
4. Went to[ Github pages](https://github.com/hfactor/sub-notes/settings/pages) settings, activated Pages.
5. Finally, modified some markdown, so that Jekyll will trigger and [create Github Page environment ](https://github.com/hfactor/sub-notes/deployments/activity_log?environment=github-pages)
6. Done! (I have CNAME already set, hence it's going to hiran.in/sub-notes)

Try this! :)

**Comment by makayla-moster** [comment]
@hfactor  Thank you! I'll check it out!

**Comment by hfactor** [comment]
There are URL-level bugs, as I have hard-coded at most places and baseurl was never considered. I will check and correct that in new version.

**Comment by hfactor** [comment]
**Subpath is fixed. Check the latest version!**
