### ISSUE TITLE
Using simply Jekyll tags

### ISSUE THREAD

**Issue by yazae** [Jekyll-Garden/jekyll-garden.github.io#18]
Hi, I love this theme, thanks a lot for releasing it.

The only additional feature I would want is the tag feature of simply jekyll.

I’m very new to jekyll and was wondering : did you remove it on purpose ? was it causing other bugs ? I will try to do it on my own but it’s a bit hard to understand the full scope of the scripts for now.

--
Thanks again, it makes a really beautiful digital garden :)

(ps: sorry if it’s not the right place to this question, I’m not fully used to the contribution/community part of github)

**Comment by yazae** [comment]
oh I just readed this on you Jekyll Garden Features page, sorry I had apparently skipped this part :

## Limitations : Tags

This theme doesn't support #tags inside the story. Tags using frontend YAML is possible, but it will be a single file index as auto-generating pages per Tag is complex using Github pages. (I might add this in the next version, if I can crack how to, and if there is a demand)

What do you mean about "story" ? The feed ?

**Comment by hfactor** [comment]
Hi @yazae, thanks for the kind words. 

I removed tags because of two reasons. 
1. Tag is not a standard practice in markdown. It's a product (Obsidian or whatever markdown editor you are using) feature. I am trying to stick with markdown as much as possible, to reduce product dependency. 
2. Tags in Jekyll is a YAML feature, ie, something you need to add as part of the front matter, which is an extra step. 

These days on my notes, I consider Tags as a first-class entity, and I have created a set of notes to link based on category/topic. (Check my [notes](https://hiran.in/notes), you will see a private link at end of all notes, starting with § symbol). I am considering moving those files to the public and making a [MOC](https://forum.obsidian.md/t/on-the-process-of-making-mocs/1060) page.
