### ISSUE TITLE
Burger navbar does not work

### ISSUE THREAD

**Issue by synthbiont** [Jekyll-Garden/jekyll-garden.github.io#28]
Hey! Thanks a lot for developing this template. I like it a lot, and I have used it for my own digital garden. 

I am having problems with the navbar on mobile. Although it is visible, when clicking on it there is no menu or list of links that is shown. It is something that does not work on the demo website of the theme, or in your personal website.

I am new at making websites, so I cannot really help by providing a solution to this issue. Maybe you, or anyone that has forked this template, could give a hand?

**Comment by hugo655** [comment]
Hey! I just started dabbing this template, but noticed too the "Burguer Menu" isn't  working for mobile devices.

**Comment by efemkay** [comment]
Hi @synthbiont @hugo655 . I faced similar issue and had a look at what's causing it -- it turns out the js file needed for the hamburger menu wasn't properly loaded. I've created PR to fix the issue, hope the dev ok with it n merge it.

Anyway, in case it takes time, here's the fix (it's a simple one)
- in your repo, edit the following file `_includes/Nav.html`
- add the following lines after line 36 (which a script loading for modeswitcher.js)
    - `<script src="{{ site.baseurl }}/assets/js/Hamburger.js"></script>`
- save it and push it back to your repo

> since i've fixed it for my repo, you can try it out my digital garden https://efemkay.github.io/digital-garden/
> make the browser window narrower if you're browsing from a desktop to trigger the hamburger menu

here's a screenshot for guide
![image](https://user-images.githubusercontent.com/42369515/181918573-bbd83ca6-cebf-48e0-a156-933cfde16c68.png)

**Comment by hfactor** [comment]
Thanks, @efemkay for the patch. I have accepted your PR. <3
